# CONFIG FOR SNAPHU
# ---------------------------------------------------------------- 
# Created by SNAP software on: 00:22:34 01/07/2026
#
# Command to call snaphu:
# 
#       snaphu -f snaphu.conf Phase_ifg_IW3_VV_23Jun2026_24Jun2026.snaphu.img 23665

#########################
# Unwrapping parameters #
#########################

STATCOSTMODE 	 DEFO 
INITMETHOD  	 MCF 
VERBOSE 	 TRUE 

###############
# Input files #
###############

CORRFILE 		coh_IW3_VV_23Jun2026_24Jun2026.snaphu.img

################
# Output files #
################

OUTFILE 		UnwPhase_ifg_IW3_VV_23Jun2026_24Jun2026.snaphu.img
LOGFILE 		snaphu.log

################
# File formats #
################

INFILEFORMAT 	FLOAT_DATA
CORRFILEFORMAT 	FLOAT_DATA
OUTFILEFORMAT 	FLOAT_DATA

###############################
# SAR and geometry parameters #
###############################

TRANSMITMODE 	REPEATPASS

ORBITRADIUS 	7075556.634
EARTHRADIUS 	6377439.218

LAMBDA 			0.0554658

BASELINE 		89.485
BASELINEANGLE_RAD 	3.312

NEARRANGE 		901073.1966152

# Slant range and azimuth pixel spacings
DR 				2.3295621
DA 				15.617876

# Single-look slant range and azimuth resolutions.
RANGERES 		2653030.6018487
AZRES 			82.0119491

# The number of independent looks: approximately equal to the
#     real number of looks divided by the product of range and
#     azimuth resolutions, and multiplied by the product of the
#     single-look range and azimuth spacings. It is about 0.53
#     times the number of real looks for ERS data processed
#     without windowing.
NCORRLOOKS 		23.8

################
# Tile control #
################

NTILEROW           10
NTILECOL           10

ROWOVRLP           0
COLOVRLP           0 

NPROC              4

TILECOSTTHRESH   500

# End of snaphu configuration file